### ISSUE TITLE
docker-compose 1.29 required

### ISSUE THREAD

**Issue by andreas-p** [greenbone/docs#230]
The install documentation at https://greenbone.github.io/docs/latest/21.4/container/index.html#installing-docker-compose states that docker-compose 1.27 is required (which would be provided by bullseye-backports). This is actually not sufficient: since `service_completed_successfully` is used, the minimum required version is 1.29.

**Comment by bjoernricks** [comment]
Thanks for letting us know. I've updated the docs accordingly which will be published when the PR gets merged.
