### ISSUE TITLE
Differences between dependencies for building and for operating recognizable 

### ISSUE THREAD

**Issue by Dexus** [greenbone/docs#25]
### Expected behavior

That the Docs showing me, what I really need to build the binaries and what I really need to run the binary. 

### Actual behavior

Currently all are deps for build and run are mixed deps.

**Comment by bjoernricks** [comment]
Yes it is a documentation for building the GVM stack from source not for packaging. It doesn't differentiate between build and runtime dependencies. So this is wont fix from my side.
