### ISSUE TITLE
Typo error in some containers' description

### ISSUE THREAD

**Issue by rompish-tv** [greenbone/docs#323]
### Expected behavior

In docs/src/22.4/container/index.md , some containers' description should contain "Shows the license and **exits** afterwards."

### Actual behavior

In docs/src/22.4/container/index.md , some containers' descriptions contain "Shows the license and exi**s**ts afterwards." 
This is saying the opposite of their actual behavior.

### Steps to reproduce

Go to the containers documentation, to the "Description" paragraph. There are several descriptions concerned.

**Comment by y0urself** [comment]
Hey thank you for your Issue! Feel free to create a PR on your own to fix this! :)

**Comment by y0urself** [comment]
addressed in #324
