### ISSUE TITLE
Remove MQTT port mapping in    image: greenbone/mqtt-broker

### ISSUE THREAD

**Issue by TiloGit** [greenbone/docs#366]
https://github.com/greenbone/docs/blob/c48f9d0b5a03ac4e2855d8847e5a95d73d4e998c/src/_static/docker-compose-22.4.yml#L140

see also: https://forum.greenbone.net/t/mqtt-without-authentication/13647/10

cause `MQTT Broker Does Not Require Authentication` triggering otherwise.

**Comment by TiloGit** [comment]
@bjoernricks could please update docker-compose yaml file if appropriate. Thanks.

**Comment by bjoernricks** [comment]
@TiloGit feel free to provide a PR.

**Comment by huornlmj** [comment]
This is a security issue - shouldn't it at least be given some priority or at least warn the end user they have an mqtt server hanging out onto the network for no reason?
