### ISSUE TITLE
manual feed sync instructions incorrect for docker containers

### ISSUE THREAD

**Issue by bwittmeyer** [greenbone/docs#367]
### Expected behavior
docker-compose -f $DOWNLOAD_DIR/docker-compose.yml -p greenbone-community-edition \
    run --rm ospd-openvas greenbone-nvt-sync

manual update of greenbone feeds

### Actual behavior
manual update will fail since greenbone-nvt-sync and greenbone-feed-sync are nolonger part of the ospd-openvas and gvmd containers.

Fix update documentation to remove this reference.  Alternatively update the documentation to explain what would be required to use the new greenbone-feed-sync python script running on the host.

**Comment by huornlmj** [comment]
Is this solved?

**Comment by bwittmeyer** [comment]
Not rally,
No updates were made documention. There was a reference to a new
greenbone-feede-sync container however no details on how to use it,

**Comment by bjoernricks** [comment]
No this isn't solved. My commit should just have referenced this issue but not closed it.
