### ISSUE TITLE
The official tool for managing multi-container Docker applications is "docker-compose" with a hyphen ("-"). 

### ISSUE THREAD

**Issue by syspect-sec** [greenbone/docs#388]
### Expected behavior

Docker workflow commands in the documentation should work. 

### Actual behavior

The `docker-compose` commands in the documentation were all changed to `docker compose` recently. 
The official tool for managing multi-container Docker applications is "docker-compose" with a hyphen ("-").

**Comment by syspect-sec** [comment]
I didn't see that the install method for Docker tools had changed in the docs, so this is not an issue with the changed install method.

**Comment by bjoernricks** [comment]
Some background. `docker-compose` was implemented in Python. Docker Inc. (the company) decided to replace the Python based docker compose with a plugin directly integrated into the Docker CLI written in golang. The Python docker compose (the one with the hyphen) is called docker compose v1 now and the new version (without the hyphen) is called docker compose v2. v1 will not get any updates and all users are encouraged to update to v2. See https://docs.docker.com/compose/compose-file/

![grafik](https://github.com/greenbone/docs/assets/897575/7630cec1-a347-47b7-859c-87fa9db606af)
