### ISSUE TITLE
Suggest this be moved to the top of the page under a new TL;DR section

### ISSUE THREAD

**Issue by huornlmj** [greenbone/docs#395]
https://github.com/greenbone/docs/blob/ba8fcefd522becb69cc853f274372860f09d736b/src/22.4/container/index.md?plain=1#L98

**Comment by y0urself** [comment]
A TL;DR is not intended to be on the top of a page.
We do not want to encourage community users to skip our documentation as it contains valuable information and reduces frequently asked questions.
