### ISSUE TITLE
Web port bound to all interfaces,  documentation should reflect this

### ISSUE THREAD

**Issue by huornlmj** [greenbone/docs#398]
https://github.com/greenbone/docs/blob/ba8fcefd522becb69cc853f274372860f09d736b/src/_static/docker-compose-22.4.yml#L92
The web ui interface is bound to all interfaces but the documentation says

```
xdg-open "http://127.0.0.1:9392" 2>/dev/null >/dev/null &
```
This is misleading and makes the end user think that the service is only bound to loopback.  Either the documentation should state to use the host name or reconfigure the deployment to bind the web ui port to loopback for security purposes.

**Comment by bjoernricks** [comment]
With #405 I've changed the compose file to listen only on the local interface of the docker host now.
